version: 2
jobs:
  test:
    docker:
    - image: circleci/golang
    steps:
    - checkout
    - run:
        name: Download dependencies
        command: go mod download
    - run:
        name: Test
        command: go test -cover -v ./...

workflows:
  version: 2
  build-workflow:
    jobs:
      - test